---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu/xenial64
  - name: centos/7
  - name: my/win2016
    transport:
      name: winrm
      elevated: true
      customize:
        memory: 8192
      vm_hostname: mywinvm

suites:
  - name: default
    run_list:
      - recipe[setupweb::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
