AWSTemplateFormatVersion: '2010-09-09'
Description: Network Stack CFN for TCI
Parameters:
  MyIPAddr:
    Type: String
    Default: '173.70.126.112/32'

Resources:
  TCIVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.32.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
      - Key: Name 
        Value: ToolChainInc-VPC
      - Key: Tool
        Value: CFN
  TCINetACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcID: !Ref TCIVPC
      Tags:
      - Key: Name
        Value: ToolChainInc-NetworkACL
      - Key: Tool
        Value: CFN
  TCINACLInHTTP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref TCINetACL
      RuleNumber: '100'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: !Ref MyIPAddr 
      PortRange:
        From: '80'
        To: '80'
  TCINACLInHTTPS:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref TCINetACL
      RuleNumber: '110'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: !Ref MyIPAddr
      PortRange:
        From: '443'
        To: '443'
  TCINACLInSSH:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref TCINetACL
      RuleNumber: '120'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: !Ref MyIPAddr
      PortRange:
        From: '22'
        To: '22'
  TCINACLInRDP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref TCINetACL
      RuleNumber: '130'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: !Ref MyIPAddr
      PortRange:
        From: '3389'
        To: '3389'
  TCINACLInWINRM:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref TCINetACL
      RuleNumber: '140'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: !Ref MyIPAddr
      PortRange:
        From: '5985'
        To: '5986'
  TCINACLInCustomTCP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref TCINetACL
      RuleNumber: '150'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: '0.0.0.0/0'
      PortRange:
        From: '1025'
        To: '65535'
Outputs:
  TCIVPCID:
    Description: VPC ID for ToolChain, Inc.
    Value: !Ref TCIVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
